name: NBTNexus
version: 1.0.0
main: de.ancash.nbtnexus.NBTNexus
depend: [ILibrary]
api-version: 1.13

commands:
   nbtn:
      usage:
      - "ยง7/nbtn edit (edit item in hand in gui)"
      - "ยง7/nbtn s/ser/serialize (serialize item in hand to json & yaml)"