name: NBTNexus
version: 1.1.0
main: de.ancash.nbtnexus.NBTNexus
depend: [ILibrary, ProtocolLib]
api-version: 1.13
author: [Ancash]

commands:
   nbtn:
      usage:
      - "ยง7/nbtn edit (edit item in hand in gui)"
      - "ยง7/nbtn s/ser/serialize (serialize item in hand to json & yaml)"
      - "ยง7/nbtn tsdc (measures ser/de time)"