name: NBTNexus
version: 1.0.0
main: de.ancash.nbtnexus.NBTNexus
#depend: [ILibrary, ProtocolLib]
api-version: 1.13

commands:
   nbtn:
      usage:
      - "ยง7/nbtn edit"
   serde:
      usage: "/serde"
   deserialize:
   